// All in-game text goes through here so it uses the bitmap font (generated by tools/fonts/).
export const FONT_KEY = 'pixel_operator_8';
export const FONT_SIZE = 8; // native size; use integer multiples (16, 24...) to stay crisp

/** Bitmap text with a 1px dark drop shadow for readability. Color is a tint (0xRRGGBB). */
export function pixelText(scene, x, y, text, { size = FONT_SIZE, color = 0xffffff, align = 0 } = {}) {
  return scene.add
    .bitmapText(Math.round(x), Math.round(y), FONT_KEY, text, size, align)
    .setTint(color)
    .setDropShadow(size / FONT_SIZE, size / FONT_SIZE, 0x000000, 1);
}

/** Width in px of a single line of bitmap text. */
export function textWidth(scene, text, size = FONT_SIZE) {
  const data = scene.cache.bitmapFont.get(FONT_KEY).data;
  const scale = size / data.size;
  let w = 0;
  for (const ch of text) w += (data.chars[ch.codePointAt(0)]?.xAdvance ?? 0) * scale;
  return w;
}

/** Greedy word wrap to maxWidth px (keeps existing line breaks). Returns the text with '\n' inserted. */
export function wrapText(scene, text, maxWidth, size = FONT_SIZE) {
  return text
    .split('\n')
    .map((paragraph) => {
      const lines = [];
      let line = '';
      for (const word of paragraph.split(' ')) {
        const attempt = line ? `${line} ${word}` : word;
        if (line && textWidth(scene, attempt, size) > maxWidth) {
          lines.push(line);
          line = word;
        } else {
          line = attempt;
        }
      }
      lines.push(line);
      return lines.join('\n');
    })
    .join('\n');
}
