// All in-game text goes through here so it uses the bitmap font (generated by tools/fonts/).
export const FONT_KEY = 'pixel_operator_8';
export const FONT_SIZE = 8; // native size; use integer multiples (16, 24...) to stay crisp

/** Bitmap text with a 1px dark drop shadow for readability. Color is a tint (0xRRGGBB). */
export function pixelText(scene, x, y, text, { size = FONT_SIZE, color = 0xffffff, align = 0 } = {}) {
  return scene.add
    .bitmapText(Math.round(x), Math.round(y), FONT_KEY, text, size, align)
    .setTint(color)
    .setDropShadow(size / FONT_SIZE, size / FONT_SIZE, 0x000000, 1);
}
